[package]
name = "monocli"
version = "0.1.0"
edition = "2021"
authors =  ["incredimo <a@xo.rs>"]

[dependencies]
chrono = "0.4.38"
plotters = "0.3.6"
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde_json = "1.0.122"
zip = "2.1.6"
